details_query = {

"GET_INDIRECT_CODES": """SELECT * FROM INDIRECT""",
"GET_SITES": """SELECT ID AS [value], SITE_NAME AS [label] FROM SITE""",
"GET_WAREHOUSES": """SELECT ID AS [value], DESCRIPTION AS [label] FROM WAREHOUSE""",


"GET_LABOR_TICKETS": """SELECT 
                        ULAB.TRANSACTION_ID, ULAB.WORKORDER_BASE_ID,  
                        CONCAT(CONVERT(VARCHAR(10), ULAB.WORKORDER_LOT_ID), ' - ', CONVERT(VARCHAR(10), ULAB.WORKORDER_SPLIT_ID), ' - ',  CONVERT(VARCHAR(10), ULAB.WORKORDER_SUB_ID)) AS [LOT_SPLIT_SUB],
                        CAST(ULAB.CLOCK_IN AS DATE) AS [CLOCK_IN_DATE], CONVERT(VARCHAR(8), ULAB.CLOCK_IN, 108) AS [CLOCK_IN_TIME], CAST(ULAB.CLOCK_OUT AS DATE) AS [CLOCK_OUT_DATE], CONVERT(VARCHAR(8), ULAB.CLOCK_OUT, 108) AS [CLOCK_OUT_TIME],
                        ULAB.HOURS_WORKED, 
                        CASE WHEN ULAB.APPROVED = 0 THEN 'false'
                            WHEN ULAB.APPROVED = 1 THEN 'true' ELSE 'false' END AS [APPROVED] ,
                        ULAB.APPROVED_AT, ULAB.APPROVED_BY,
                        ULAB.DESCRIPTION AS [LAB_DESC], ULAB.UDF1, ULAB.UDF2, ULAB.UDF3, ULAB.UDF4, ULAB.WORK_LOCATION, ULAB.REGULAR_TIME, ULAB.OVER_TIME, ULAB.DOUBLE_TIME, ULAB.QA_NOTES,
                        WO.PART_ID, WO.DESIRED_QTY, CAST(WO.DESIRED_WANT_DATE AS DATE) AS [DESIRED_WANT_DATE], WO.STATUS, WO.ENGINEERED_BY, WO.ACT_MATERIAL_COST, WO.ACT_LABOR_COST, WO.ACT_SERVICE_COST, 
                        CO.ID, CO.CUSTOMER_ID, CO.CUSTOMER_PO_REF, CO.STATUS, CO.TOTAL_AMT_ORDERED, CO.TOTAL_AMT_SHIPPED, PART.DESCRIPTION
                        FROM UNI_LABOR_TICKET ULAB
                        LEFT JOIN WORK_ORDER WO ON WO.BASE_ID = ULAB.WORKORDER_BASE_ID AND WO.LOT_ID = ULAB.WORKORDER_LOT_ID AND WO.SPLIT_ID = ULAB.WORKORDER_SPLIT_ID AND WO.SUB_ID = ULAB.WORKORDER_SUB_ID
                        LEFT JOIN DEMAND_SUPPLY_LINK DSL ON DSL.SUPPLY_BASE_ID = ULAB.WORKORDER_BASE_ID AND DSL.SUPPLY_LOT_ID = ULAB.WORKORDER_LOT_ID AND DSL.SUPPLY_SPLIT_ID = ULAB.WORKORDER_SPLIT_ID AND DSL.SUPPLY_SUB_ID = ULAB.WORKORDER_SUB_ID
                        LEFT JOIN PART ON PART.ID = WO.PART_ID
                        LEFT JOIN CUSTOMER_ORDER CO ON CO.ID = DSL.DEMAND_BASE_ID
                        WHERE CONVERT(DATE, TRANSACTION_DATE) BETWEEN '{FROM_DATE}' AND '{TO_DATE}' {EMP_ID_QUERY_STRING} {APPROVED_QUERY_STRING}""",

}