details_query = {

"GET_INDIRECT_CODES": """SELECT * FROM INDIRECT""",
"GET_SITES": """SELECT ID AS [value], SITE_NAME AS [label] FROM SITE""",
"GET_WAREHOUSES": """SELECT ID AS [value], DESCRIPTION AS [label] FROM WAREHOUSE""",


"GET_LABOR_TICKETS": """SELECT * 
                        FROM [UNI_LABOR_TICKET]
                        WHERE CONVERT(DATE, TRANSACTION_DATE) = '{DATE}' {EMP_ID_QUERY_STRING} {APPROVED_QUERY_STRING}""",

}