parcel_query = {

"SEARCH_PARCEL": """SELECT * 
                    FROM PARCELS 
                    WHERE TSRID LIKE '{TEXT}' OR STATE LIKE '{TEXT}' OR MUNICIPALITY LIKE '{TEXT}' 
                    OR LOCATION_FULL_STREET_ADDRESS LIKE '{TEXT}' OR UNIQUE_ID LIKE '{TEXT}' """,

"GET_PARCELS_BASED_ON_FILTERS": """SELECT * 
                    FROM PARCELS 
                    WHERE STATE LIKE '{STATE}' {COUNTY} {MUNICIPALITY} {STATUS} """,


"GET_DISTINCT_STATES": """SELECT DISTINCT STATE FROM PARCELS""",
"GET_DISTINCT_COUNTY": """SELECT DISTINCT COUNTY FROM PARCELS""",
"GET_DISTINCT_MUNICIPALITY": """SELECT DISTINCT MUNICIPALITY FROM PARCELS""",

"GET_PARCEL_BY_ID": """SELECT * FROM PARCELS WHERE UNIQUE_ID = '{ID}'""",
"GET_PARCEL_FEES_BY_ID": """SELECT * FROM FEES WHERE UNIQUE_ID = '{ID}' AND IS_ACTIVE = '1'""",

"UPDATE_STATUS_BY_ID": """UPDATE PARCELS SET STATUS = '{STATUS}' WHERE UNIQUE_ID = '{ID}'""",

"UPDATE_FEES_BY_ID": """UPDATE FEES
                    SET CATEGORY = '{CATEGORY}', DESCRIPTION = '{DESCRIPTION}', AMOUNT = '{AMOUNT}', INTEREST_ACC_INTERVAL = 'per_diem',
                    INTEREST = '{INTEREST}', EFFECTIVE_DATE = '{EFFECTIVE_DATE}', EFFECTIVE_END_DATE = '{EFFECTIVE_END_DATE}'
                    WHERE ID = '{ID}'""",

"DELETE_FEES_BY_ID": """UPDATE FEES SET IS_ACTIVE = '0' WHERE ID = {ID};""",

"INSERT_FEES_BY_UNIQUE_ID": """
                        INSERT INTO FEES
                        (`UNIQUE_ID`, `CATEGORY`, `DESCRIPTION` , `AMOUNT`, `INTEREST`, `INTEREST_ACC_INTERVAL`, `EFFECTIVE_DATE`, `EFFECTIVE_END_DATE`)
                        VALUES
                        ( '{UNIQUE_ID}', '{CATEGORY}', '{DESCRIPTION}' ,'{AMOUNT}', '{INTEREST}', 'per_diem', '{EFFECTIVE_DATE}', '{EFFECTIVE_END_DATE}');"""


}