quote_query = {

"GET_ALL_ACTIVE_CUSTOMERS": """SELECT ID AS [value], NAME AS [label] FROM CUSTOMER WHERE ACTIVE_FLAG = 'Y'""",
"GET_SALES_REP": """SELECT ID AS [value], NAME AS [label] FROM SALES_REP WHERE NAME IS NOT NULL""",
"GET_TERRITORY": """SELECT CODE AS [value], CODE AS [label] FROM TERRITORY""",
"GET_FOB_POINT": """SELECT CODE AS [value], CODE AS [label] FROM FOB_POINT""",
"GET_SHIP_VIA": """SELECT CODE AS [value], CODE AS [label] FROM SHIP_VIA"""
}